from sqlalchemy import Column, DateTime, String
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from database.db import Base

class ChatSession(Base):
    __tablename__ = 'chat_sessions'

    # session_id is a UUID generated by the client that's why it's a string
    session_id = Column(String, primary_key=True)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    last_active = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationship to link messages to this chat session
    messages = relationship("Message", back_populates="chat_session")
