from sqlalchemy import Column, DateTime, ForeignKey, String, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from database.db import Base

class Message(Base):
    __tablename__ = 'messages'

    # message_id and session_id is a UUID generated by the client that's why it's a string
    message_id = Column(String, primary_key=True)
    session_id = Column(String, ForeignKey('chat_sessions.session_id'))

    message_type = Column(String)
    content = Column(Text)
    timestamp = Column(DateTime(timezone=True), server_default=func.now())

    chat_session = relationship("ChatSession", back_populates="messages")
